Without, if user does not provide an argument it resolves in a cryptic error
const name = process.argv[2].replace(/(\W+)/gi, '_');
                             ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at file:///Users/maerch/Git/background-removal-js/scripts/changelog/create.mjs:11:30
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)